- action:
  - data:
      message: Zone Change Notification
      title: Zone Notification
    service: notify.pb
  id: '1519084803422'
  alias: Zone Notification
  condition: []
  trigger:
  - entity_id: device_tracker.nexus6p
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.nexus6p
    event: enter
    platform: zone
    zone: zone.work
  - entity_id: device_tracker.nexus6p
    event: leave
    platform: zone
    zone: zone.home
  - entity_id: device_tracker.nexus6p
    event: leave
    platform: zone
    zone: zone.work
- action:
  - data:
      message: HomeAssistant Started
      title: HomeAssistant Notification
    service: notify.pb
  alias: HomeAssistant Notification
  condition: []
  id: '1519084809287'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      message: Time to give Dexie her insulin shot.
      title: Dexie's Insulin Reminder
    service: notify.pb
  alias: Dexie Notification
  condition: []
  id: '1519085145538'
  trigger:
  - at: 07:30
    platform: time
  - at: '19:30'
    platform: time
- id: '1526082360186'
  alias: IR Motion
  trigger:
  - entity_id: binary_sensor.pin3
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: zone
    entity_id: device_tracker.nexus6p
    zone: zone.home
  action:
  - data:
      entity_id: switch.pin18
    service: switch.toggle
- action:
  - data:
      message: Coinbase wallet change!
      title: LTC Wallet
    service: notify.pb
  id: '1526141197358'
  alias: LTC Wallet
  trigger:
  - below: '.01'
    entity_id: sensor.coinbase_ltc_wallet
    platform: numeric_state
  - below: '.01'
    entity_id: sensor.coinbase_bch_wallet
    platform: numeric_state
  - below: '.01'
    entity_id: sensor.coinbase_eth_wallet
    platform: numeric_state
  condition: []
- alias: Power state on HA start-up
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/power1
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/power2
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/Power3
      payload: ''
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/power4
      payload: ''
  id: 664c50ca2ec64ff9ba9b1a77eca098e2
- id: '1531398651929'
  alias: Sonoff
  trigger:
  - entity_id: switch.sonoff
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: switch.sonoff
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: switch.nodemcu
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: switch.nodemcu
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: toggled
      title: sonoff
    service: notify.pb
