homeassistant:
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 200
  name: Home
  unit_system: imperial
  time_zone: America/Chicago
  temperature_unit: F
  customize: !include customize.yaml

config:

hassio:

automation: !include automations.yaml

http:
  api_password: !secret http_password
  base_url: http://dhahaj.duckdns.org:8123/
  use_x_forwarded_for: True

recorder:
  purge_keep_days: 2

# sensor:
#   - platform: pi_hole

# wemo:
#   static:
#     - 192.168.0.38
#discovery:
# shopping_list:

updater:
  include_used_components: true

history:

logger:
  default: error
  logs:
    homeassistant.components.switch.hook: debug

# logbook: !include logbook.yaml

frontend:
  themes:
    greeny:
      primary-color: green
    black:
      primary-color: black
    bluesky:
      primary-color: blue
    purple:
      primary-color: purple
    orange:
      primary-color: orange
 
coinbase:
  api_key: !secret cb_key
  api_secret: !secret cb_secret
  exchange_rate_currencies:
    - BTC
    - BCH
    - ETH
    - LTC

sun:
map:
zone: !include zones.yaml

device_tracker:
  - platform: gpslogger
    icon: mdi:android
    password: !secret gpspass

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: http://dhahaj.duckdns.org:8321
    # url: http://192.168.0.194:8321
  sincos:
    title: SinCos
    icon: mdi:buddhism
    url: https://www.openprocessing.org/sketch/544500#
  router_remote:
    title: TP-Link
    icon: mdi:access-point-network
    url: http://dhahaj.duckdns.org:9090
  tasmoadmin:
    title: Sonoff
    icon: mdi:lightbulb-on
    url: http://192.168.0.194:9541
    # url: http://dhahaj.duckdns.org:9541
  # grafana:
  #   title: Grafana
  #   icon: mdi:chart-timeline
  #   url: http://dhahaj.duckdns.org:3000
  # influxdb:
  #   title: InFluxDB
  #   url: http://dhahaj.duckdns.org:8887
  # pihole:
  #   title: Pi-hole
  #   icon: mdi:block-helper
  #   url: http://192.168.0.194/admin/index.php

discovery:
  # enable:
  #   - belkin_wemo
  #   - philips_hue
  #   - plex_mediaserver
  #   - samsung_tv
  #   - sonos

# media_player:
#   - platform: gpmdp
#     host: 192.168.1.1

notify:
  - platform: pushbullet
    name: pb
    api_key: !secret pushbullet_api

switch: 
  - platform: tplink
    host: 192.168.0.189
    name: HS100
 # - platform: hook
  #  name: Hook
#    token: !secret hook_token
  - platform: rpi_gpio
    name: Pin18
    ports:
      18: pin18
 # - platform: mqtt
 #   name: "Sonoff power"
#    state_topic: "stat/sonoff/POWER"
 #   command_topic: "cmnd/sonoff/POWER"
 #   availability_topic: "tele/sonoff/LWT"
 #   qos: 1
 #   payload_on: "ON"
 #   payload_off: "OFF"
  #  payload_available: "Online"
  #  payload_not_available: "Offline"
 #   retain: false

binary_sensor:
  - platform: rpi_gpio
    pull_mode: DOWN
   # invert_logic: false
    ports:
     3: pin3
    
weblink:
  entities:
    - name: Remote Home Router
      url: https://75.1.37.24:21747/
    - name: HomeAssistant.io
      url: https://home-assistant.io
    - name: NodeMCU
      url: http://dhahaj.duckdns.org:7777/
    - name: Archer-C9
      url: http://dhahaj.duckdns.org:9090/
    # - name: IDE
    #   url: http://dhahaj.duckdns.org/ide.html

#alarm_control_panel:
#  - platform: manual_mqtt
#    state_topic: home/alarm
#    command_topic: home/alarm/set
#    pending_time: 60
#    trigger_time: 1800
#    disarm_after_trigger: false
#    delay_time: 30
#    armed_home:
#      pending_time: 0
#      delay_time: 0
#    armed_away:
#      pending_time: 60
#      delay_time: 30

# panel_custom:
#   - name: react
#     sidebar_title: Example Panel
#     sidebar_icon: mdi:checkbox-marked-outline
#     # url_path: todomvc
#     config:
#       title: Wow hello!

#mqtt:
 # discovery: true
 # discovery_prefix: homeassistant
  # host: localhost
  # broker: domus1
  # port: 1883
  # client_id: home-assistant-1
  # keepalive: 60
  # username: homeassistant
  # password: !secret http_password
  # protocol: 3.1.1
  # birth_message:
  #   topic: "tele/hass1/LWT"
  #   payload: "Online"
  #   qos: 1
  #   retain: true
  # will_message:
  #   topic: "tele/hass1/LWT"
  #   payload: "Offline"
  #   qos: 1
  #   retain: true
    

#mqtt:
#  broker: core-mosquitto
#  username: !secret mqtt_username
#  password: !secret mqtt_password

# mqtt:
  # broker: 192.168.0.104
  # client_id: 123456789
  
# camera:
#   - platform: rpi_camera
#     name: RaspberryPi Cam
#     vertical_flip: 1
#     horizontal_flip: 1
#     image_quality: 5
    #file_path: /tmp/camera.jpg
    #  - platform: usps
    #scan_interval: 10

# panel_iframe:
#   configurator:
#     title: Configurator
#     icon: mdi:wrench
#     url: http://127.0.0.1:3218

# sensor:
#   platform: example

#usps:
# username: !secret usps_username
#  password: !secret usps_password

      #android_ip_webcam:
      #  - host: 192.168.0.166
      #    port: 8080
      #    name: AndroidWebCam
      #    scan_interval: 10
      #    sensors:
      #      - audio_connections
      #      - battery_level
      #      - motion
      #    switches:
      #      - focus
      #      - night_vision
      #      - overlay
      #      - torch
      #      - video_recording
    # motion_sensor:

